name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e

            cd ${{ secrets.SSH_PROJECT_PATH }} || (
            echo "Проект не найден. Клонируем репозиторий..."
            git clone https://github.com/${{ github.repository }} ${{ secrets.SSH_PROJECT_PATH }}
            cd ${{ secrets.SSH_PROJECT_PATH }}
            npm install)
            
            echo "Проект найден. Обновляем..."
            git fetch --all
            git reset --hard origin/main
            npm install --no-save

            if [ -f app.pid ]; then
              echo "Останавливаем старый процесс..."
              kill \$(cat app.pid) || true
              rm app.pid
            fi

            echo "Запуск нового процесса..."
            nohup npm start > app.log 2>&1 &
            echo \$! > app.pid

            if ps -p \$(cat app.pid) > /dev/null; then
              echo "Сервис успешно запустился!"
            else
              echo "Ошибка при запуске сервиса!"
              exit 1
            fi

            echo "Проверка доступности сервиса..."
            if curl --silent --fail http://localhost:3000 > /dev/null; then
              echo "Сервис доступен!"
            else
              echo "Сервис не доступен!"
              exit 1
            fi
          EOF
