name: Deploy to VPS

on:
  push:
    branches:
      - main   # или твоя прод-ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e

            # Если проект не клонирован — клонировать
            if [ ! -d "${{ secrets.SSH_PROJECT_PATH }}" ]; then
              echo "Проект не найден. Клонируем репозиторий..."
              git clone https://github.com/${{ github.repository }} ${{ secrets.SSH_PROJECT_PATH }}
            else
              echo "Проект найден. Обновляем..."
              cd ${{ secrets.SSH_PROJECT_PATH }}
              git pull origin main
            fi

            # Перейти в папку проекта
            cd ${{ secrets.SSH_PROJECT_PATH }}

            # Установить зависимости
            npm install

            # Остановить старый процесс, если запущен
            if [ -f app.pid ]; then
              kill \$(cat app.pid) || true
              rm app.pid
            fi

            # Запустить новый процесс через nohup
            nohup npm start > app.log 2>&1 &
            echo \$! > app.pid
          EOF
