name: Deploy to VPS

on:
  push:
    branches:
      - main   # или другая твоя ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e

            cd ${{ secrets.SSH_PROJECT_PATH }}

            git pull origin main

            npm install

            if [ -f app.pid ]; then
              kill \$(cat app.pid) || true
              rm app.pid
            fi

            nohup npm start > app.log 2>&1 &
            echo \$! > app.pid
          EOF
