name: Manual Nginx Setup

description: 'Настройка nginx на сервере через SSH вручную'

on:
  workflow_dispatch:

jobs:
  setup-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Подключиться по SSH и настроить nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx certbot python3-certbot-nginx
            sudo bash -c 'cat > /etc/nginx/sites-available/skillchecker.tech <<NGINX_CONF
server {
listen 80;
server_name skillchecker.tech www.skillchecker.tech;
location / {
proxy_pass http://localhost:5005;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
}
NGINX_CONF'
            echo "==== Содержимое nginx-конфига ===="
            cat /etc/nginx/sites-available/skillchecker.tech
            sudo ln -sf /etc/nginx/sites-available/skillchecker.tech /etc/nginx/sites-enabled/skillchecker.tech
            sudo nginx -t
            sudo systemctl reload nginx
            sudo certbot --nginx --non-interactive --agree-tos --redirect -m brov.ko@ya.ru -d skillchecker.tech -d www.skillchecker.tech
            sudo nginx -t
            sudo systemctl reload nginx
            echo "nginx + HTTPS настроен для skillchecker.tech -> localhost:5005"
